# Generated by Django 2.2.19 on 2021-05-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20210426_1802'),
        ('forms', '0009_form__is_deleted'),
    ]

    operations = [
    ]
